server:
  port: 8080
spring:
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    cache: false
    mode: HTML
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 40MB
  cache:
    type: ehcache
    ehcache:
      config: ehcache.xml
    cache-names: user-cache,dict-cache
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/findlover?useSSL=false&useUnicode=true&characterEncoding=UTF-8  # your profile
      username: root # your profile
      password: 123456 # your profile
      initial-size: 1
      min-idle: 1
      max-total: 2
      max-wait-millis: 6000

fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:
    width: 150
    height: 150
  trackerList: 58.87.118.28:22122 # your profile

mybatis:
  type-aliases-package: com.hpe.findlover.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    cache-enabled: true


pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

mapper:
  mappers:
    - com.hpe.util.BaseTkMapper
  not-empty: false
  identity: MYSQL
